DROP TABLE IF EXISTS Klient CASCADE;

CREATE TABLE Klient
(
	isik_id bigint NOT NULL,
	KLIENDI_SEISUNDI_LIIGI_KOOD smallint NOT NULL DEFAULT 1,
	on_nous_tylitamisega boolean NOT NULL DEFAULT false,
	CONSTRAINT PK_Klient PRIMARY KEY (isik_id),
	CONSTRAINT FK_Klient_Kliendi_seisundi_liik FOREIGN KEY (KLIENDI_SEISUNDI_LIIGI_KOOD) REFERENCES Kliendi_seisundi_liik (KLIENDI_SEISUNDI_LIIGI_KOOD) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Klient_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE No Action ON UPDATE No Action
);

CREATE INDEX IXFK_Klient_Kliendi_seisundi_liik ON Klient (KLIENDI_SEISUNDI_LIIGI_KOOD ASC);