DROP TABLE IF EXISTS Riik CASCADE;

CREATE TABLE Riik
(
	RIIGI_KOOD varchar(3)	 NOT NULL,
	nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Riik PRIMARY KEY (RIIGI_KOOD),
	CONSTRAINT UC_RIIGI_NIMETUS UNIQUE (nimetus),
	CONSTRAINT CK_RIIGI_RIIGI_KOOD CHECK (nimetus !~ '^[[:space:]]*$'),
  CONSTRAINT CK_RIIGI_NIMETUS CHECK (nimetus::text ~ '^[A-Z]{3}$')
);