-- drop unused jhi and auth tables/columns
DROP TABLE jhi.jhi_user;
DROP SEQUENCE public.sequence_generator;

-- fix constraints, inconsistent names, etc
ALTER TABLE public.isik ADD CONSTRAINT ck_isik_pildi_aadress CHECK (pildi_aadress!~'^[[:space:]]*$');
ALTER TABLE public.isik ADD CONSTRAINT ck_isik_keelekood CHECK (keelekood!~'^[[:space:]]*$');
ALTER TABLE public.isik ADD CONSTRAINT ck_isik_aktiveerimise_voti CHECK (aktiveerimise_voti!~'^[[:space:]]*$');
ALTER TABLE public.isik ADD CONSTRAINT ck_isik_reset_voti CHECK (reset_voti!~'^[[:space:]]*$');
ALTER TABLE public.isik ADD CONSTRAINT ck_isik_kasutajanimi CHECK (kasutajanimi!~'^[[:space:]]*$');
ALTER TABLE jhi.jhi_authority ADD CONSTRAINT ck_jhi_authority_name CHECK (name!~'^[[:space:]]*$');
ALTER TABLE jhi.jhi_persistent_audit_event ADD CONSTRAINT ck_jhi_persistent_audit_event_principal CHECK (principal!~'^[[:space:]]*$');
ALTER TABLE jhi.jhi_persistent_audit_event ADD CONSTRAINT ck_jhi_persistent_audit_event_event_type CHECK (event_type!~'^[[:space:]]*$');
ALTER TABLE jhi.jhi_persistent_audit_evt_data ADD CONSTRAINT ck_jhi_persistent_audit_evt_data_name CHECK (name!~'^[[:space:]]*$');
ALTER TABLE jhi.jhi_persistent_audit_evt_data ADD CONSTRAINT ck_jhi_persistent_audit_evt_data_value CHECK (value!~'^[[:space:]]*$');

ALTER TABLE jhi.jhi_persistent_audit_event SET (FILLFACTOR=90);
ALTER TABLE jhi.jhi_persistent_audit_evt_data SET (FILLFACTOR=90);

ALTER TABLE jhi.jhi_persistent_audit_event
  ALTER COLUMN event_id
  ADD GENERATED BY DEFAULT
  AS IDENTITY;


